# Lecture 1: August 7th, 2023

## Welcome to Math 10!

__Today:__
* Introductions and mood check-in 
* Syllabus read-through + what is specifications grading?
* Canvas tour 
* Review of Python and NumPy

__Typical Lecture Schedule:__ 
* 12:00pm-1:00pm: Lecture Part 1
* 1:00pm-1:05pm: Scream into void break
* 1:05pm-1:50pm: Lecture Part 2

![mood.png](mood.png)

Results from our intro activity. Glad to see no angry faces :)

## Introduction to Deepnote

This is an example of a markdown cell. Markdown cells are used to write explanation for your code and format text nicely.

For example, if you are familiar with HTML, many things work exactly the same. For example:
* This is an example of making a list.
* Here is another list element
To execute a cell, I can press `command+enter`. To edit a cell, make sure it's highlighted, and then press enter.

If you're familiar with $\LaTeX$, here's how we can use it:
* `$\int_0^1 x^2 dx$` gives the following output $\int_0^1 x^2 dx$.

Here's an example of how we can change text color:

<font color = red> Warning: </font> Many commands work the same in Deepnote as in HTML and Jupyter notebook. However, there are a few differences. If you know how to do something in HTML or Jupyter and it's not working in Deepnote, it's probably a syntax difference.

Now, let's look at some examples of code cells.

In [1]:
2 + 2 

4

In [2]:
a = 3
b = 7 
a + b 

10

The next thing I want to emphasize is that the order in which we evaluate cells matters!

In [ ]:
# This is an example of a comment
# Notice, there's no checkmark at the bottom of this cell
# It means I have no run this block of code
c = 3

In [3]:
# The following will give an error
# Note: for those new to python, ** gives exponentiation
c**3

NameError: name 'c' is not defined

In [4]:
c = 3

In [5]:
c**3

27

## Review of Concepts from Python

* NumPy is one of the most important python libraries
* Functionally, it is very similar to MATLAB
* NumPy does not come with base python, we will need to import it every time we start a new notebook

The abbreviation `np` is a standard convention, and we will always use it in Math 10.

In [6]:
import numpy as np

* Using NumPy, make a length-1000 array of random real numbers between 0 and 10.

In [7]:
# Instantiate a random number generator (rng) object
rng = np.random.default_rng()

To get random real numbers, we use the `random` method of `rng`.

In [12]:
#generates a random real number between 0 and 1
rng.random()

0.7940334806679044

In [13]:
rng.random(5)

array([0.22943134, 0.34644041, 0.26016189, 0.30596756, 0.21569321])

In [14]:
rng.random(5).shape

(5,)

Recall, `rng.random()` returns random real numbers between 0 and 1. To get between 0 and 10, what could we do?

In [16]:
10*rng.random(10)

array([6.46001595, 0.14496367, 7.22340817, 3.49796514, 4.27865984,
       9.29187813, 3.00996986, 4.36312117, 8.14376895, 5.03279479])

In [19]:
arr = 10*rng.random(1000)

Base python has a number of built-in functions, here are two examples:

In [20]:
len(arr)

1000

In [21]:
max(arr)

9.996451492899073

In [22]:
help(rng.integers)

Help on built-in function integers:

integers(...) method of numpy.random._generator.Generator instance
    integers(low, high=None, size=None, dtype=np.int64, endpoint=False)
    
    Return random integers from `low` (inclusive) to `high` (exclusive), or
    if endpoint=True, `low` (inclusive) to `high` (inclusive). Replaces
    `RandomState.randint` (with endpoint=False) and
    `RandomState.random_integers` (with endpoint=True)
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype. If `high` is None (the default), then results are
    from 0 to `low`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is 0 and this value is
        used for `high`).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribut

In [23]:
# Include 1, go up to, but don't include 5
# size is 7 by 3
rng.integers(1,5,size=(7,3))

array([[3, 2, 1],
       [2, 1, 3],
       [4, 4, 1],
       [2, 2, 1],
       [4, 3, 4],
       [4, 1, 4],
       [4, 1, 2]])

In [25]:
# Notice the following gives a mistake
rng.integers(1,5,7,3)

TypeError: Cannot interpret '3' as a data type

In [26]:
# don't need the size keyword here
rng.integers(1,5,(7,3))

array([[1, 1, 2],
       [3, 4, 2],
       [4, 2, 4],
       [4, 1, 4],
       [3, 2, 4],
       [2, 2, 2],
       [2, 2, 2]])

Very good question asked in the chat: what is the difference between shape `(5,)` and `(1,5)`

* `(5,)` This shape means I have a 1-dimensional NumPy array. You might get a shape like this if you convert a list to a NumPy array.

In [31]:
mylist = [3,1,4,1,5]
arr = np.array(mylist)
arr

array([3, 1, 4, 1, 5])

In [32]:
arr.shape

(5,)

* `(1,5)` We can turn a shape of `(5,)` into this shape. Notice, it increases the number of dimensions from 1 to 2.

In [34]:
arr2 = arr.reshape((1,5))
arr2

array([[3, 1, 4, 1, 5]])

There's no real difference in this simple example, but many NumPy methods require us to have at least 2 dimensions.

* What proportion of elements in this array are strictly greater than 7?

In [35]:
arr = 10*rng.random(1000)

In [37]:
# This is an example of something called slicing
# Here, we take the first 10 elements of arr
arr[:10]

array([6.10294932, 5.05930354, 5.42719265, 2.78312014, 0.99534937,
       3.90058562, 6.74241116, 6.78971087, 7.13295903, 1.15773805])

In [36]:
arr > 7

array([False, False, False, False, False, False, False, False,  True,
       False,  True, False, False,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True, False,  True,
        True,  True, False,  True, False,  True, False, False, False,
       False, False, False, False,  True, False,  True,  True, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False,  True,
       False,  True,  True, False, False, False, False, False, False,
        True, False, False, False, False,  True,  True, False, False,
        True,  True, False, False, False, False, False, False,  True,
       False, False,  True, False,  True, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False,  True,  True, False, False, False,  True, False,  True,
       False, False,  True,  True,  True, False, False,  True,  True,
       False, False,

Just like in MATLAB, True is treated like 1, and False is treated like 0.

In [38]:
True + True 

2

In [39]:
False + True

1

First, let's count all the elements which are greater than 7.

In [40]:
sum(arr > 7)

294

Now, we look at the proportion of these elements in `arr`.

In [41]:
sum(arr > 7)/len(arr)

0.294

Notice that we got about 30%. This makes sense, given how we coded `arr`. Do you see why?

* <font color = red> Convert the array to a list and answer the same question. </font> (We'll get to this example next time.)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=1a65427d-3a14-44b2-a47b-772f41a8699f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>